export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_NEEDS_SUCCESS = 'LOAD_NEEDS_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_NEED_SUCCESS = 'CREATE_NEED_SUCCESS';
export const UPDATE_NEED_SUCCESS = 'UPDATE_NEED_SUCCESS';

/******************User info********************* */

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

